controller:
  image:
    repository: registry.k8s.io/ingress-nginx/controller
    tag: "v1.10.1"

  service:
    type: NodePort
    ports:
      http: 80
      https: 443
    nodePorts:
      http: 30080
      https: 30443

  rbac:
    create: true

  serviceAccount:
    create: true
