service:
  name: k8s-backend-backend
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: kooco-group
  hosts:
    - host: www.kooco.click
      paths:
        - path: /*
          pathType: ImplementationSpecific
    - host: kooco.click
      paths:
        - path: /*
          pathType: ImplementationSpecific
