apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  namespace: spring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: www.kooco.click
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" . }}
                port:
                  number: 8080
          - path: /actuator/health
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" . }}
                port:
                  number: 8080
          - path: /healthz
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fullname" . }}
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" . }}
                port:
                  number: 8080

