apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koco-spring-ingress
  namespace: spring-backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: koco-spring
            port:
              number: 80
# TLS 사용 시
# tls:
# - hosts:
#   - api.koco.click
#   secretName: api-koco-click-tls

