apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.kooco.click
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: spring-svc
                port:
                  number: 80
          - path: /health
            pathType: Exact
            backend:
              service:
                name: spring-svc
                port:
                  number: 80
