apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.kooco.click
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: k8s-dev-k8s-dev  # Helm 템플릿 결과에 맞춰 수정
                port:
                  number: 8080
          - path: /health(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: k8s-dev-k8s-dev  # 동일 서비스
                port:
                  number: 8080
