apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - host: www.kooco.click
      http:
        paths:
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: spring-svc
                port:
                  number: 80
          - path: /health/*
            pathType: Prefix
            backend:
              service:
                name: spring-svc
                port:
                  number: 80
