# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "k8s-dev.fullname" . }}
#   labels:
#     app: app
# spec:
#   selector:
#     app: app  # ← Deployment의 label과 일치해야 함
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 8080
#       protocol: TCP
#   type: {{ .Values.service.type }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dev.fullname" . }}
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: k8s-dev-k8s-dev  # 실제 deployment의 selector에 맞게 설정
  ports:
    - name: http
      protocol: TCP
      port: 80        # 외부에서 접근할 포트
      targetPort: 8080  # 파드 내부에서 사용하는 포트
