apiVersion: v1Add commentMore actions
kind: Service
metadata:
  name: {{ include "k8s-dev.fullname" . }}
  labels:
    app: app
spec:
  selector:
    app: app  # ← Deployment의 label과 일치해야 함
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.service.type }}
