image:
  repository: 266735804784.dkr.ecr.ap-northeast-2.amazonaws.com/dev-k8s
  tag: latest

env:
  SPRING_DATASOURCE_URL: ""
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
  
service:
  type: ClusterIP
  port: 8080

redis:
  image: redis:7
  port: 6379

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: kooco-group

controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443 
