image:
  repository: 266735804784.dkr.ecr.ap-northeast-2.amazonaws.com/dev-k8s
  tag: latest

env:
  SPRING_DATASOURCE_URL: ""
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"

service:
  type: ClusterIP
  port: 8080

redis:
  image: redis:7
  port: 6379

ingress:
  enabled: true
  className: nginx  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 
  hosts:
    - host: www.kooco.click 
      paths:
        - path: /
          pathType: Prefix
  tls: []  #


